version: "3"
services:
  node-app:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/simplecrud
      - /simplecrud/node_modules
    depends_on:
      - mongo
    command: npm run dev
  mongo:
    image: mongo:latest
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ragul
      MONGO_INITDB_ROOT_PASSWORD: mypassword

    ports:
      - 27017:27017
    volumes:
      - database-data:/data/db
  mongo-express:
    image: mongo-express:latest
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ragul
      ME_CONFIG_MONGODB_ADMINPASSWORD: mypassword
      ME_CONFIG_MONGODB_URL: mongodb://ragul:mypassword@mongo:27017/

volumes:
  database-data:

    